name: Generate Github-Pages from markdown files

on:
  push:
    branches: [ release ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/checkout@v2

      - name: Run Export
        run: |
          export TZ='Asia/Shanghai'
          npm install
          npm run build
      - name: Deploy Github-Pages
        uses: JamesIves/github-pages-deploy-action@4.2.5
        with:
          github_token: ${{ secrets.first_test }}
          deploy_key: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages
          folder: .vuepress/dist

